RIT-EVT/EVT-core

README.md, cmake/evt-core_compiler.cmake
Improve windows support. Add ".exe" suffix to compilation tools on windows systems. Improve Windows build documentation.
=> Improve Windows build support

.github/workflows/cmake.yml, cmake/evt-core_clang-format.cmake, include/EVT/dev/IWDG.hpp
Created a GitHub Workflow to check if PRs can build successfully and match coding standards
Edited clang-format documentation
=> Can GitHub Build It? Yes, GitHub Can!

.github/workflows/cmake.yml, include/EVT/dev/IWDG.hpp
Fixes problem with GitHub Build not being able to push formatting changes
=> Change Reference for GitHub Checkout

.github/workflows/cmake.yml, cmake/evt-core_clang-format.cmake
Fixed the clang-format CMake file to work in projects other than EVT-Core
=> Cross-Project Formatting

include/EVT/io/CAN.hpp, include/EVT/io/platform/f3xx/CANf3xx.hpp, samples/can/back_and_forth/main.cpp, samples/can/loopback/main.cpp, samples/canopen/main.cpp, src/io/platform/f3xx/CANf3xx.cpp
Adds error handling for the CAN interface.
* Creates an enum for possible CAN errors
* Have each method return a CAN status
*  **New methods connect and disconnect** so that we can handle possible HAL errors starting CAN
* Update samples to handle possible errors
=> No IT for this (CAN) Network

CMakeLists.txt, cmake/evt-core_compiler.cmake
Move the logic for selecting the board into the compiler cmake file so that other projects can select different platforms to build for.
=> CMake up your mind

include/EVT/io/PWM.hpp, include/EVT/io/platform/f3xx/PWMf3xx.hpp, samples/pwm/main.cpp, src/io/platform/f3xx/PWMf3xx.cpp
- Optimized the PWM module by replacing float usages with uint32_t
- Microseconds are passed in to the setPeriod function now
- Duty Cycle percentage is now specified as an integer
=> Pushing 🅿️WM Improvements

samples/button_debounce/main.cpp, src/dev/button.cpp
- Converted HAL_GetTick calls used in the button class and its samples to use EVT's millis function found in time utils
=> Can I copy your button debounce? Sure, just change it so it isn't obvious. 

include/EVT/io/manager.hpp, include/EVT/io/pin.hpp, samples/spi/ADXL345/main.cpp, samples/spi/SPI_With_Arduino/main.cpp, src/io/platform/f3xx/SPIf3xx.cpp
Added SPI support for the STM32F334x8. Also added the template for SPI in Half-Duplex mode.
=> mjh9585/f334 SPI

.github/workflows/cmake.yml
Added GitHub build testing for the F334
=> Polyamorous Building

samples/pwm/main.cpp, src/io/platform/f3xx/PWMf3xx.cpp
Fixed the PWM equations to work with fixed point correctly
=> Fixed Fixed Point Point

samples/canopen/TestCanNode.hpp, src/io/platform/f3xx/CANf3xx.cpp
Fixed CAN filter and Corrected example TPDO to include Node ID
=> CAN filter and Example TPDO Node ID

cmake/evt-core_compiler.cmake
Quick PR to change the default target device and provide some helpful debug output
=> Please CMake Some Sense

CMakeLists.txt, include/EVT/io/I2C.hpp, include/EVT/io/SPI.hpp, include/EVT/io/UART.hpp, include/EVT/io/platform/f3xx/I2Cf3xx.hpp, include/EVT/io/platform/f3xx/SPIf3xx.hpp, include/EVT/io/platform/f3xx/UARTf3xx.hpp, src/io/I2C.cpp, src/io/SPI.cpp, src/io/UART.cpp, src/io/platform/f3xx/I2Cf3xx.cpp, src/io/platform/f3xx/SPIf3xx.cpp, src/io/platform/f3xx/UARTf3xx.cpp
Changed I2C and SPI Timeouts to be adjustable with a #define
=> When the Time is Out

include/EVT/dev/LCD.hpp, samples/lcd/lcd-segment/main.cpp, src/dev/LCD.cpp
Removed the weird flashing from the HUDL. Did this by simply removing the DISPLAYOFF signal that was sent every time something was drawn to the screen.
Tested all samples and the HUDL still functions like expected.
=> Flash me one last time

samples/i2c/main.cpp, src/io/I2C.cpp
readReg() method modified for multibyte i2c reads
=> I too (2) can now see (C) multiple bytes

include/EVT/io/platform/f3xx/UARTf3xx.hpp, include/EVT/manager.hpp, src/io/platform/f3xx/UARTf3xx.cpp
=> U ARen'T Reading the Documentation

include/EVT/io/CAN.hpp, src/io/platform/f3xx/CANf3xx.cpp
Added variable CAN Timeout, so boards can have different timeouts if needed
=> CAN for 100 secs

include/EVT/io/SPI.hpp, include/EVT/io/pin.hpp, include/EVT/io/platform/f3xx/SPIf3xx.hpp, include/EVT/io/platform/f4xx/SPIf4xx.hpp, include/EVT/manager.hpp, samples/lcd/basic/main.cpp, samples/lcd/lcd-alphabet/main.cpp, samples/lcd/lcd-ball/main.cpp, samples/lcd/lcd-counter/main.cpp, samples/lcd/lcd-evt-logo/main.cpp, samples/lcd/lcd-more-sections/main.cpp, samples/lcd/lcd-segment/main.cpp, samples/spi/ADXL345/main.cpp, samples/spi/SPI_With_Arduino/main.cpp, src/io/platform/f3xx/SPIf3xx.cpp, src/io/platform/f4xx/SPIf4xx.cpp
=> F4xx SPI Support. Was too easy. didn't get enough time to hate myself and think of a pun

CMakeLists.txt, include/EVT/dev/platform/f4xx/RTCf4xx.hpp, include/EVT/manager.hpp, samples/rtc/main.cpp, src/dev/platform/f3xx/RTCf3xx.cpp, src/dev/platform/f4xx/RTCf4xx.cpp
:) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) …
=> F4xx RTC Support

README.md
I'm so good at adding F4xx support i did it to a text document
=> New and Improved Read Me Plus! (Added F4xx Support for Read Me)

include/core/dev/MCUTimer.hpp, include/core/manager.hpp, src/core/dev/Encoder.cpp, src/core/io/platform/f4xx/SPIf4xx.cpp, src/core/io/platform/f4xx/UARTf4xx.cpp
Went to fix F4 UART missing switch statement and got carried away. Most compilation warnings are gone, including a missing SPI method, obviously the missing uart switch statement, a random encoder driver method fix (wow wonder who made that method originally).
=> FWT-73 Variety is the Driver Fixes of Life

CMakeLists.txt, include/core/rtos/Timer.hpp
Turns out my previous fix did not fix as much as it appeared. This one should! Hopefully...
=> Can Make RTOS work? (CMake RTOS bugfix) 🐛🔨
