CMakeLists.txt
cmake/evt-core_build.cmake
include/EVT/io/manager.hpp
include/EVT/platform/f3xx/stm32f302x8.hpp
samples/adc/CMakeLists.txt
samples/adc/main.cpp
samples/blink/CMakeLists.txt
samples/blink/main.cpp
samples/can/CMakeLists.txt
samples/can/main.cpp
samples/echo/CMakeLists.txt
samples/echo/main.cpp
samples/i2c/CMakeLists.txt
samples/i2c/main.cpp
samples/pwm/CMakeLists.txt
samples/pwm/main.cpp
samples/queue/CMakeLists.txt
samples/queue/main.cpp
samples/read_write/CMakeLists.txt
samples/read_write/main.cpp
src/io/platform/f3xx/f302x8/ADCf302x8.cpp
src/platform/f3xx/stm32f302x8.cpp

We are ready for our first "official release" 0.1.0 which is currently based off of `dev/0.0.2` will include everything from `dev/0.0.2` as well as the clean up commits I have made. The idea is that EVT-core is now feature complete enough to start writing various board in EVT-core. v0.1.0 will be the starting point from which to start development.
We will continue to make tweaks until EVT-core is considered "stable" (no longer having large scale changes), At which point we will have our 1.0.0 release.
The main things added in the cleanup are
1. A macro for creating an executable that  can be used to flash a board
2. Creation of a system level init function which handles initializing the board including clock settings

Release the code

---

cmake/evt-core_compiler.cmake
include/EVT/io/UART.hpp

- Small updates.  Added include so `size_t` type was visible to APM code in UART.hpp
- Updated linelength param for cpplint to 120

Added import and updated linelength cpplint param

---

cmake/evt-core_compiler.cmake

Quick tweak that removes unused code from libraries during compilation, significantly saves space in final binary.

Linkin Logs

---

include/EVT/io/platform/f3xx/f302x8/ADCf302x8.hpp
samples/adc/main.cpp
src/io/platform/f3xx/f302x8/ADCf302x8.cpp

Fixed the bug where the ADC would not generate the correct values.  
- The main fix applied was to only run the ADC for the number of conversions as ADC channels configured.  
- The DMA buffer was also updated to have this same effective size.
- Some modifications were also made to stop and de-init peripherals when adding new channels.

Bug fix/dpopp/adc dma

---

include/EVT/io/I2C.hpp
include/EVT/io/platform/f3xx/f302x8/I2Cf302x8.hpp
samples/i2c/main.cpp
src/io/I2C.cpp
src/io/platform/f3xx/f302x8/I2Cf302x8.cpp

This PR adds error handling to the I2C interface. Each I2C method now returns an I2CStatus. "Return" values are now passed in via a pointer and updated indirectly. This is a common practice in C/C++ especially in the Linux kernel. This allows us to now tell when an error has taken place and respond accordingly.
For now, only the I2C interface has been updated to have the error handling. But in the future all interfaces will have it. So be critical as this system will then be used throughout EVT-core with each interface having a "status" that is returned. This will then extend to include the devices as well.

I2C and Error

---

include/EVT/dev/storage/EEPROM.hpp
include/EVT/dev/storage/M24C32.hpp
src/dev/storage/M24C32.cpp

Change the size of the address size for reading and writing data from `uint8_t` to `uint32_t` to allow for EEPROM sizes larger then 256 bytes.

Who took a byte out of my EEPROM size?

---

include/EVT/io/CANopen.hpp

Increase the size of CANopen related data. This includes increasing the size of the CANopen buffer and updating the canopen submodule to include code that increases the size of the SDO buffer.

Kicking the bigger CAN

---

README.md
src/io/platform/f3xx/I2Cf3xx.cpp

Enables the clock for the I2C in the 334.
NOTE: The system won't compile for the 334 until the SPI PR is merged in.

"I2C doesn't work", "Well did you turn it on?"

---

include/EVT/io/GPIO.hpp
include/EVT/io/manager.hpp
include/EVT/io/platform/f3xx/GPIOf3xx.hpp
src/io/GPIO.cpp
src/io/platform/f3xx/GPIOf3xx.cpp

Add the ability to specify a pull direction (up, down, no pull) on GPIOs. Defaults to the previous hard coded value of `PULL_DOWN`.

Pulling us in a new direction

---

src/io/platform/f3xx/CANf3xx.cpp

Added a timeout in the HAL_CAN_GetTxMailboxesFreeLevel while loop. This allows us to overwrite the full mailboxes if there is no CAN network available.

✉️ Mail Forgery ✉️

---

src/io/I2C.cpp

Fixed a bug in I2C readReg()
It was using the length of the data output as the number of registers to read from, which was creating situations where it was accessing random memory locations

🐛 :hammer:

---

include/EVT/dev/IWDG.hpp
include/EVT/dev/platform/f3xx/IWDGf3xx.hpp
samples/iwdg/main.cpp
src/dev/platform/f3xx/IWDGf3xx.cpp

Added init() function to start the running of the watchdog timer sometime after the class has been instantiated
Needed for the BMS to work properly
(Also fixed a mistake I made when I modified the class a year ago, which completely broke it)

Nice dog, innit?

---

include/EVT/dev/Encoder.hpp
src/dev/Encoder.cpp

Added the ability to dynamically change the encoder range and position. This is important for the general use case of an encoder being used as an input device to a UI, because different UI menus may have different numbers of options.
I should have implemented this in the original pull request, but I forgor.
Also removed an hpp method that wasn't implemented anymore.

This Encoder is Driving me crazy (Dynamically!)

---

include/EVT/dev/Encoder.hpp
include/EVT/dev/button.hpp
src/dev/Encoder.cpp
src/dev/button.cpp

Bugfix for the encoder class (was modding by range instead of range + 1).
Also fixed some return values for functions, the getPosition() should have been a uint32_t all along I'm just dumb as hell.
Also added the ability to define what GPIO state (high or low) is considered "pressed" for button.hpp.

I am encoding buttons to be high 🔨 🐛 

---

cmake/evt-core_compiler.cmake

Added a memory summary to the cmake build configuration to print memory usage for each target. Also added an option to force color output when using the command line with ninja. 
- Added memory usage summary to builds
- Added FORCE_COLORED_OUTPUT option to always colorize build output

Making Better Options

---

.gitignore
include/core/io/CAN.hpp
include/core/io/platform/f3xx/CANf3xx.hpp
include/core/io/platform/f4xx/CANf4xx.hpp
include/core/manager.hpp
samples/can/CMakeLists.txt
samples/can/back_and_forth/main.cpp
samples/can/multiCAN/CMakeLists.txt
samples/can/multiCAN/README.md
samples/can/multiCAN/main.cpp
src/core/io/platform/f4xx/CANf4xx.cpp

Adds dual CAN bus support for STM32F446xx in EVT-core.
- Adds base CAN bus support to STM32F446xx 
- Support CAN 1 hardware
- Support CAN 2 hardware
- Allows simultaneous CAN bus usage on both interfaces

FWT-16 We CAN do 2 For 4

---

CMakeLists.txt

The RTOS stuff wasn't building when EVT-core was used as a library in another project, turns out I should have used CMAKE_CURRENT_LIST_DIR instead of CMAKE_SOURCE_DIR. Silly me!
Anyway here's a whole pr for literally less than one line of changes.
Tested one both EVT-core and when using EVT-core as a library, this change makes it build correctly both ways.

Really Tiny One Small Change (to) My Asinine Keywords Excellently 🐛 🔨 

---

include/core/utils/types/FixedQueue.hpp

Fixed the include for FixedQueue, changing it from stdint.h to cstddef, which actually works. For some reason in EVT-core it worked the old way even though it should not have, but it doesn't work outside of EVT-core (or at least in VCU, where I encountered this issue).

Fixing Queue

---

include/core/io/CAN.hpp
src/core/io/platform/f4xx/CANf4xx.cpp

For interrupts to work with Threadx, there's a specific Threadx method that needs to be called at the beginning of the interrupt, and then another that needs to be called at the end of the interrupt. To enable this functionality (and other functionalities in the future), there are now two macros that you can define:
CAN_IRQ_PRE_INTERRUPT_ROUTINE
and
CAN_IRQ_POST_INTERRUPT_ROUTINE
each of which kind of do what it seems like they do.
NOTE: this probably won't make CANOpen work nicely with RTOS in terms of thread safety, but should at least prevent it from immediately crashing.

CAN you stop Interrupting me! I'm doing an Enhancement!

---

src/core/rtos/Threadx.cpp

Tiny change to bulk initialize, now the debug failure messages contain the name of the thing that failed.

Really Trying to Operate Safely

---

README.md

As far as I know (from looking through the files), CAN, Timer, and RTC all look like they are now supported by F4. Please correct me if I am wrong!

Updating the README's list of what F446 supports.
